<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>pamp_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Lang\en.json" />
    <None Remove="Lang\pl.json" />
    <None Remove="LICENSE.txt" />
    <None Remove="manifest.json" />
    <None Remove="pamp_icon.png" />
    <None Remove="pamp_logo_min.png" />
    <None Remove="pl.png" />
    <None Remove="Resources\localhost.png" />
    <None Remove="Resources\off.png" />
    <None Remove="Resources\on.png" />
    <None Remove="Resources\pma.png" />
    <None Remove="Resources\sql_shell.png" />
    <None Remove="Resources\www_dir.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Lang\en.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Lang\pl.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="LICENSE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="pamp_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="pamp_icon.png" />
    <Resource Include="pamp_logo_min.png" />
    <Resource Include="pl.png" />
    <Resource Include="Resources\localhost.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\off.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\on.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\pma.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\sql_shell.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\www_dir.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
